services:
    chimera:
        image: cefriel/minimal-chimera-quarkus:temurin-17
        build:
            context: ../../
            dockerfile: ./Temurin/example-quarkus/Dockerfile
        ports:
            - "127.0.0.1:8085:8085"
        volumes:
#              - ./data:/home/data
            - ./outbox:/home/out
        environment:
            - TZ=Europe/Rome