services:
    chimera:
        image: cefriel/minimal-chimera-spring:temurin-17
        build:
            context: ../../
            dockerfile: ./Temurin/example-spring/Dockerfile
        volumes:
#              - ./data:/home/data
              - ./outbox:/home/out
        environment:
              - TZ=Europe/Rome
