version: "3.8"

services:
    chimera:
        image: cefriel/minimal-chimera:graalvm-17
        build:
            context: ../
            dockerfile: ./GraalVM/Dockerfile
        volumes:
#              - ./data:/home/data
              - ./outbox:/home/out
        environment:
              - TZ=Europe/Rome
