version: "3.8"

services:
    chimera:
        image: cefriel/chimera-deployment-templates:graalvm
        build:
            context: ../
            dockerfile: ./Dockerfile
        volumes:
              - ./appFolder:/home/appFolder
              - ./outbox:/home/out
        environment:
              - TZ=Europe/Rome
