services:
    chimera:
        image: cefriel/minimal-chimera:graalvm-17
        build:
            context: ../../
            dockerfile: ./GraalVM/example/Dockerfile
        volumes:
#              - ./data:/home/data
              - ./outbox:/home/out
        environment:
              - TZ=Europe/Rome
